{
  "formatVersion": "1.1",
  "component": {
    "group": "com.magic.sdk",
    "module": "AdsSdk",
    "version": "v2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-lite",
          "version": {
            "requires": "22.6.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx",
          "version": {
            "requires": "18.6.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "AdsSdk-v2.0.2.aar",
          "url": "AdsSdk-v2.0.2.aar",
          "size": 746559,
          "sha512": "aff06abc079e0d5e69ef77823c724c3066d676697ab89730a307e960b64683ec6dcc7bf1815916768c176dbf47c2918d5c47ececd66095e5f7706d2311ff7388",
          "sha256": "9054913e42f92a7e3d4ee0481038add1b26ae8ddafb82f48c0134e3f64033729",
          "sha1": "ea73e6e4f0562fa13005d5c4576a2c0c71dfdbe0",
          "md5": "e52d168f540916bbf61823862555ddbe"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics-ktx",
          "version": {
            "requires": "21.5.1"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-ads",
          "version": {
            "requires": "22.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.facebook.shimmer",
          "module": "shimmer",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcodex",
          "version": {
            "requires": "1.31.1"
          }
        },
        {
          "group": "com.android.billingclient",
          "module": "billing-ktx",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-lite",
          "version": {
            "requires": "22.6.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-ktx",
          "version": {
            "requires": "18.6.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "AdsSdk-v2.0.2.aar",
          "url": "AdsSdk-v2.0.2.aar",
          "size": 746559,
          "sha512": "aff06abc079e0d5e69ef77823c724c3066d676697ab89730a307e960b64683ec6dcc7bf1815916768c176dbf47c2918d5c47ececd66095e5f7706d2311ff7388",
          "sha256": "9054913e42f92a7e3d4ee0481038add1b26ae8ddafb82f48c0134e3f64033729",
          "sha1": "ea73e6e4f0562fa13005d5c4576a2c0c71dfdbe0",
          "md5": "e52d168f540916bbf61823862555ddbe"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "AdsSdk-v2.0.2-sources.jar",
          "url": "AdsSdk-v2.0.2-sources.jar",
          "size": 65785,
          "sha512": "44080a638c1c1afe6eadf407cfef446c5db27af6dbbe34127b10e8faaaf8c6a74432ab8bc62284078d7c56c9b171bf61d0ba858113b76ac63283bd3fa0c45499",
          "sha256": "2c921369b65a578634fe6a9a30b9e35092af7ade8301555d6554e61e5da41c8f",
          "sha1": "b0d57dbda4ec832fab409a53f5638eed9bd3e2a9",
          "md5": "90de7f4c67fc4e2be8bb4951a8ee8a23"
        }
      ]
    }
  ]
}
